orbs:
  heroku: circleci/heroku@1.2.6
workflows:
    example-workflow:
      jobs:
        - heroku/deploy-via-git:
            api-key: '2fea22c5-ac2a-4be4-a450-a758d05071d0' 
            app-name: test 
            branch: circleci-project-setup 
